# More pi-hole info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# More unbound-docker info at  https://github.com/MatthewVance/unbound-docker/tree/master

networks:
  dns_net:
    driver: bridge
  proxy:
    external: true

services:
  pihole:
    env_file: '.env'
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
    networks:
      - dns_net
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: ${WEB_PASSWORD}
      PIHOLE_DNS_: '172.23.0.8#5353'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: 'mvance/unbound:latest'
    networks:
      - dns_net
    ports:
      - '5053:53/tcp'
      - '5053:53/udp'
    volumes:
      - './unbound:/opt/unbound/etc/unbound'
    restart: unless-stopped
